name: Release Helm Charts

# Only cut new helm charts when:
# - a new release is published
# - a maintainer runs the workflow explicitly via "gh workflow run"
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  id-token: write
  pull-requests: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout brupop
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: make install-charts-toolchain
      - run: make verify-charts
      - run: make package-charts publish-charts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_REPO_NAME: ${{ github.event.repository.name }}
